
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 19 01:31:46 CST 2021
//----------------------------------------------------

package AnalizadorJS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Let = 4;
  public static final int Require = 19;
  public static final int Class = 2;
  public static final int Entero = 48;
  public static final int True = 8;
  public static final int Incremento = 35;
  public static final int PuntoComa = 25;
  public static final int Coma = 24;
  public static final int CadenaS = 46;
  public static final int Negacion = 34;
  public static final int If = 6;
  public static final int LlaveC = 21;
  public static final int Potencia = 42;
  public static final int Decremento = 37;
  public static final int LlaveA = 20;
  public static final int Default = 16;
  public static final int Var = 3;
  public static final int CorcheC = 52;
  public static final int MenosIgual = 54;
  public static final int CorcheA = 51;
  public static final int Menos = 39;
  public static final int Mas = 38;
  public static final int Menor = 28;
  public static final int Else = 7;
  public static final int ParenC = 23;
  public static final int Break = 14;
  public static final int ParenA = 22;
  public static final int AND = 32;
  public static final int Mayor = 27;
  public static final int OR = 33;
  public static final int Punto = 44;
  public static final int Console = 17;
  public static final int IgualacionS = 55;
  public static final int While = 11;
  public static final int Division = 41;
  public static final int Cadena = 45;
  public static final int Modulo = 43;
  public static final int For = 10;
  public static final int EOF = 0;
  public static final int DosPuntos = 50;
  public static final int error = 1;
  public static final int Switch = 13;
  public static final int False = 9;
  public static final int MasIgual = 53;
  public static final int Do = 12;
  public static final int Case = 15;
  public static final int Diferencia = 31;
  public static final int MenorIgual = 30;
  public static final int Igualacion = 36;
  public static final int Const = 5;
  public static final int Identificador = 47;
  public static final int MayorIgual = 29;
  public static final int Decimal = 49;
  public static final int Multiplicacion = 40;
  public static final int Log = 18;
  public static final int Igual = 26;
}

