
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 19 01:31:46 CST 2021
//----------------------------------------------------

package AnalizadorFCA;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GraficaLineas = 15;
  public static final int Numero = 32;
  public static final int Identificador = 31;
  public static final int CadenaS = 19;
  public static final int Titulo = 7;
  public static final int PuntajeEspecifico = 10;
  public static final int ParenC = 23;
  public static final int Coma = 30;
  public static final int ParenA = 22;
  public static final int Double = 6;
  public static final int LlaveC = 21;
  public static final int GenerarReporteEstadistico = 16;
  public static final int GraficaPie = 14;
  public static final int LlaveA = 20;
  public static final int Compare = 2;
  public static final int Cadena = 18;
  public static final int TituloY = 13;
  public static final int PuntajeGeneral = 11;
  public static final int EOF = 0;
  public static final int TituloX = 12;
  public static final int Dollar = 27;
  public static final int GraficaBarras = 4;
  public static final int error = 1;
  public static final int Ejex = 8;
  public static final int Archivo = 17;
  public static final int Igual = 26;
  public static final int CorcheC = 29;
  public static final int CorcheA = 28;
  public static final int DefinirGlobales = 3;
  public static final int String = 5;
  public static final int DosPuntos = 25;
  public static final int PuntoComa = 24;
  public static final int Valores = 9;
}

